// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtratsxgwafdjwzeebul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cmF0c3hnd2FmZGp3emVlYnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDI5NjgsImV4cCI6MjA3MzUxODk2OH0.yHzkhP7vQIvzAQVb3uy_mE2oW3ES95VBbsrroAq0CSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});